name: Build PR
on:
  pull_request:
    type: [opened]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn install
        run: yarn

      - name: Yarn build
        run: yarn build
